### ISSUE TITLE
Color does not update if the color selection panel is not closed explicitly

### ISSUE THREAD

**Issue by pavsoldatov** [michalosman/etch-a-sketch#2]
Hi Michal!
I came across your project from Odin and noticed a small issue with color selection. Nice job with the project, by the way (way beyond mine).
Basically, the issue is that when I'm choosing a new color from the colorpicker panel and immediately click on a square in the grid (without closing the color panel), the color selection does not update and the previous color is fired. The color updates, though, on a second click. I had the same issue with Etch-a-Sketch too.
The issue arises from `colorPicker.onchange = (e) => setCurrentColor(e.target.value)` because onchange returns the value only after the change is committed. You should try `oninput` instead of `onchange` to account for every modification of the value.

Attached are some screenshots, hope they'll come in handy.
Hit me up, if you need help with this one.

![color1](https://user-images.githubusercontent.com/80415302/169668906-4d63f219-c774-4cd8-be78-d091f921fed0.jpg)
![color2](https://user-images.githubusercontent.com/80415302/169668903-d7abfa2a-67db-448d-b998-01481e9a55a4.jpg)
![color3](https://user-images.githubusercontent.com/80415302/169668905-fe38285f-a8ec-41c4-a21e-328fe79e6b40.jpg)
![Color4](https://user-images.githubusercontent.com/80415302/169668904-5f6bdd2f-9e3a-4fcc-89c5-9d5eb5d3c294.jpg)

**Comment by michalosman** [comment]
Fixed, thank you!
