### ISSUE TITLE
[Discussion] Design inquiry

### ISSUE THREAD

**Issue by SupraSensum** [michalosman/etch-a-sketch#4]
I'm really impressed with your project!

I recently reached this project in the TOP curriculum. I'm curious, did you incorporate any pre-built libraries, frameworks, or components, or was it entirely built from scratch?

**Comment by henrylin03** [comment]
from the script, it looks like it is entirely "from scratch" in the sense it's vanilla HTML, CSS and JavaScript. Absolutely phenomenal work by the way @michalosman !
